[package]
name = "pam-usertree-spawner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "pam_usertree_spawner"
crate-type = ["cdylib"]

[dependencies]
usertree-spawner-core = { path = "../crates/core" }
usertree-spawner-protocol = { path = "../crates/protocol" }
libc.workspace = true
